### ISSUE TITLE
Port number on Service definition

### ISSUE THREAD

**Issue by irizzant** [vfarcic/k8s-specs#7]
https://github.com/vfarcic/k8s-specs/blob/e94b4a846d10677171156689d3831d560ddf4f29/deploy/go-demo-2-scaled.yml#L23

Hello
I'm reading your DevOps 2.3 toolkit book and I came across this Deployment definition.
I was wondering, shouldn't the Deployment port be `27017` since the corresponding Service declares:
```
    spec:
      ports:
    - port: 27017
```
?

Thank you

**Comment by vfarcic** [comment]
You're right. It should have been `27017`. It's not a failure through since a Service can communicate with Pods no matter whether `containerPort` is set explicitly or not. Think of it more as a statement of intention than a requirement. It is still incorrect or, to use better words, confusing and is a typo on my part. I just pushed a fix.

**Comment by irizzant** [comment]
Thanks for the fix.

> It's not a failure through since a Service can communicate with Pods no matter whether containerPort is set explicitly or not

I suspected that since the cluster was perfectly working, If I understand correctly it looks like by defining a `port` into a Service you also define a corresponding `targetPort` (defaulting to `port` value if unspecified) so you can communicate with Pods through whatever `port` you declare in the Service, correct?

**Comment by vfarcic** [comment]
That's correct :)
